// GENERATED by gen.py. Do not edit by hand: change gen.py and re-run it.
export const LOGO = "<svg viewBox=\"0 0 34 34\" aria-hidden=\"true\"><circle cx=\"17\" cy=\"17\" r=\"15.5\" fill=\"none\" stroke=\"#1d2624\" stroke-width=\"1.4\"/><circle cx=\"17\" cy=\"17\" r=\"9.5\" fill=\"none\" stroke=\"#2f5d6b\" stroke-width=\"1.2\"/><circle cx=\"17\" cy=\"17\" r=\"4\" fill=\"#4f6b52\"/><path d=\"M17 1.5v6M17 26.5v6M1.5 17h6M26.5 17h6\" stroke=\"#1d2624\" stroke-width=\"1.2\"/></svg>";
export const NAV = [["/", "Home", null], ["Members", null, [["/committee", "Committee"], ["/members", "Member registry"]]], ["/events", "Events", null], ["Resources", null, [["/resources", "Community"], ["/readings", "Readings"], ["/teaching", "Teaching"]]], ["Join", null, [["/join", "Mailing list"], ["/register", "Register as a member"]]]];
export const MAILJS = "<script>\ndocument.querySelectorAll('a.mail').forEach(function(a){var u=a.dataset.u,d=a.dataset.d;a.href='mailto:'+u+'@'+d;if(!a.textContent.trim())a.textContent=u+'@'+d;});\ndocument.querySelectorAll('details.menu').forEach(function(d){d.addEventListener('toggle',function(){if(d.open)document.querySelectorAll('details.menu').forEach(function(o){if(o!==d)o.open=false;});});});\ndocument.addEventListener('click',function(e){if(!e.target.closest('details.menu'))document.querySelectorAll('details.menu').forEach(function(o){o.open=false;});});\n</script>";
const TEMPLATE = "<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<title>{title} \u00b7 GPS &amp; Orgs Community</title>\n<meta name=\"description\" content=\"{desc}\">\n<link rel=\"stylesheet\" href=\"/assets/site.css?v={cssv}\">\n</head>\n<body>\n<header class=\"site\"><div class=\"wrap\">\n  <a class=\"brand\" href=\"/\">{logo}<span><span class=\"name\">GPS <span>&amp;</span> Orgs</span><span class=\"tag\">Geography \u00b7 Place \u00b7 Space \u00b7 Organisations</span></span></a>\n  <nav class=\"main\" aria-label=\"Main\">{nav}</nav>\n</div></header>\n{bar}\n<main class=\"wrap\">\n{body}\n</main>\n<footer class=\"site\"><div class=\"wrap\">\n  <div>GPS &amp; Orgs Community \u00b7 Geography, Place, Space and Organisations</div>\n  <div><a href=\"/join\">Join the mailing list</a> \u00b7 <a href=\"/contact\">Contact us</a></div>\n</div></footer>\n{script}\n</body>\n</html>\n".replace("{cssv}", "45e8ab97");
export function esc(s) { return String(s ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])); }
export function navhtml(here) {
  return NAV.map(([a, b, kids]) => {
    if (!kids) return `<a href="${a}"${a === here ? ' aria-current="page"' : ''}>${b}</a>`;
    const inside = kids.some(([h]) => h === here);
    const items = kids.map(([h, t]) => `<a href="${h}"${h === here ? ' aria-current="page"' : ''}>${t}</a>`).join("");
    return `<details class="menu"><summary${inside ? ' class="current"' : ''}>${a}</summary><div class="drop">${items}</div></details>`;
  }).join("");
}
export function page({ path, title, desc, body, bar = "" }) {
  const vals = { title: esc(title), desc: esc(desc), logo: LOGO, nav: navhtml(path), bar, body, script: MAILJS };
  return TEMPLATE.replace(/\{(title|desc|logo|nav|bar|body|script)\}/g, (_, k) => vals[k]);
}
export function html(body, status = 200, headers = {}) {
  return new Response(body, { status, headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store", ...headers } });
}
